# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

ENV['COSMOS_USERPATH'] ||= File.join(File.dirname(File.expand_path(__FILE__)), '../../../spec/install')
require_relative 'config/application'

Rails.application.load_tasks
