# encoding: ascii-8bit

# Copyright 2022 Ball Aerospace & Technologies Corp.
# All Rights Reserved.
#
# This program is free software; you can modify and/or redistribute it
# under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation; version 3 with
# attribution addendums as found in the LICENSE.txt
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# Modified by OpenC3, Inc.
# All changes Copyright 2022, OpenC3, Inc.
# All Rights Reserved

version: "3.5"

services:
  openc3-ruby:
    build:
      context: "openc3-ruby"
      network: host
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
        ALPINE_BUILD: ${ALPINE_BUILD}
        APK_URL: ${APK_URL}
        RUBYGEMS_URL: ${RUBYGEMS_URL}
        OPENC3_REGISTRY: ${OPENC3_REGISTRY}
    image: "${OPENC3_REGISTRY}/openc3/openc3-ruby:${OPENC3_TAG}"

  openc3-node:
    build:
      context: "openc3-node"
      network: host
      args:
        OPENC3_REGISTRY: ${OPENC3_REGISTRY}
        OPENC3_TAG: ${OPENC3_TAG}
    image: "${OPENC3_REGISTRY}/openc3/openc3-node:${OPENC3_TAG}"
    depends_on:
      - "openc3-ruby"

  openc3-base:
    build:
      context: "openc3"
      network: host
      args:
        OPENC3_REGISTRY: ${OPENC3_REGISTRY}
        OPENC3_TAG: ${OPENC3_TAG}
    image: "${OPENC3_REGISTRY}/openc3/openc3-base:${OPENC3_TAG}"
    depends_on:
      - "openc3-ruby"

  openc3-minio:
    build:
      context: "openc3-minio"
      network: host
      args:
        OPENC3_REGISTRY: ${OPENC3_REGISTRY}

  openc3-redis:
    build:
      context: "openc3-redis"
      network: host
      args:
        OPENC3_REGISTRY: ${OPENC3_REGISTRY}

  openc3-cmd-tlm-api:
    build:
      context: "openc3-cmd-tlm-api"
      network: host
      args:
        OPENC3_REGISTRY: ${OPENC3_REGISTRY}
        OPENC3_TAG: ${OPENC3_TAG}
    depends_on:
      - "openc3-base"

  openc3-script-runner-api:
    build:
      context: "openc3-script-runner-api"
      network: host
      args:
        OPENC3_REGISTRY: ${OPENC3_REGISTRY}
        OPENC3_TAG: ${OPENC3_TAG}
    depends_on:
      - "openc3-base"

  openc3-operator:
    build:
      context: "openc3-operator"
      network: host
      args:
        OPENC3_REGISTRY: ${OPENC3_REGISTRY}
        OPENC3_TAG: ${OPENC3_TAG}
    depends_on:
      - "openc3-base"

  openc3-traefik:
    build:
      context: "openc3-traefik"
      network: host
      args:
        OPENC3_REGISTRY: ${OPENC3_REGISTRY}

  openc3-init:
    build:
      context: "openc3-init"
      network: host
      args:
        NPM_URL: ${NPM_URL}
        OPENC3_REGISTRY: ${OPENC3_REGISTRY}
        OPENC3_TAG: ${OPENC3_TAG}
    depends_on:
      - "openc3-node"
      - "openc3-base"
