FROM cosmos-base

COPY web/script_runner_api /cosmos/web/script_runner_api

RUN cd /cosmos/web/script_runner_api \
  && bundle install

WORKDIR /cosmos/web/script_runner_api
CMD bundle exec rails s -b 0.0.0.0 -p 3001