FROM cosmos-base

COPY web/script_runner_api/Gemfile /cosmos/web/script_runner_api/Gemfile

RUN cd /cosmos/web/script_runner_api \
  && bundle install

COPY web/script_runner_api /cosmos/web/script_runner_api

WORKDIR /cosmos/web/script_runner_api
CMD bundle exec rails s -b 0.0.0.0 -p 3001