source ENV['RUBYGEMS_URL']
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Ultimately we want to deploy on 3.x but we don't want to mandate it here
# ruby '3.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.1.0', '>= 6.1.3.1'

# The following gems are installed in the OpenC3 base container openc3-base
# which this Dockerfile depends on: puma, redis, nokogiri

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.7'
# Use prometheus-client for /metrics
gem 'prometheus-client', '~> 2.1.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.9.3', require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors', '~> 1.1'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails', "~> 4.0.0"
  gem 'simplecov', '~> 0.20'
  gem 'codecov', '~> 0.4'
end

group :test do
  gem 'mock_redis'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data'

if ENV['OPENC3_DEVEL']
  gem 'openc3', :path => ENV['OPENC3_DEVEL']
elsif ENV['OPENC3_PATH']
  gem 'openc3', :path => ENV['OPENC3_PATH']
else
  gem 'openc3', '5.0.6.pre.beta0'
end
