source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Ultimately we want to deploy on 2.7 but we don't want to mandate it here
# ruby '2.7.0'

# gem 'nokogiri', '~> 1.10.9' # Comes with COSMOS

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.1.0', '>= 6.1.3.1'
# Use Puma as the app server

# gem 'puma', '~> 4.1' # Comes with COSMOS
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0' # Comes with COSMOS
# Use prometheus-client for /metrics
gem 'prometheus-client', '~> 2.1.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.9.3', require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors', '~> 1.1'

group :development do
  gem 'ruby-debug-ide', '~> 0.7.2'
  # This is the only version of this gem that works with Ruby 3.x
  gem 'debase', '0.2.5.beta2'
end

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails', "~> 4.0.0"
  gem 'simplecov', '~> 0.20'
  gem 'codecov', '~> 0.4'
end

group :test do
  gem 'mock_redis'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data'

if ENV['COSMOS_DEVEL']
  gem 'cosmos', :path => ENV['COSMOS_DEVEL']
elsif ENV['COSMOS_PATH']
  gem 'cosmos', :path => ENV['COSMOS_PATH']
else
  gem 'cosmos', '~> 5'
end
