source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# ruby '2.7.0'

gem 'dotenv-rails', require: 'dotenv/rails-now'

# gem 'nokogiri', '~> 1.10.9' # Comes with COSMOS

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.1.0', '>= 6.1.3.1'
# Use Puma as the app server

# gem 'puma', '~> 4.1' # Comes with COSMOS
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0' # Comes with COSMOS
# Use prometheus-client for /metrics
gem 'prometheus-client', '~> 2.1.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.2', require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors', '~> 1.1'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data'

gem 'aws-sdk-s3', '~> 1.67'
gem 'ffi'
gem 'childprocess', '~> 3'

if ENV['COSMOS_DEVEL']
  gem 'cosmos', :path => ENV['COSMOS_DEVEL']
elsif ENV['COSMOS_PATH']
  gem 'cosmos', :path => ENV['COSMOS_PATH']
else
  gem 'cosmos', '~> 5'
end
