#!/usr/bin/env ruby
# encoding: ascii-8bit

# Copyright 2014 Ball Aerospace & Technologies Corp.
# All Rights Reserved.
#
# This program is free software; you can modify and/or redistribute it
# under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 3 with
# attribution addendums as found in the LICENSE.txt

require_relative 'autohotkey.rb'
autohotkey('CmdSequence', 'cmd_sequence.ahk') do
  require 'cosmos/tools/cmd_sequence/cmd_sequence'
  require 'cosmos/tools/cmd_tlm_server/cmd_tlm_server_gui'
  Cosmos::CmdSequence.run
end

# Remove generated sequences
%w(sequence.txt test_sequence.txt).each do |filename|
  path = File.join("autohotkey", "outputs", "sequences", filename)
  File.delete path if File.exist? path
end
