#!/usr/bin/env ruby
# encoding: ascii-8bit

# Copyright 2014 Ball Aerospace & Technologies Corp.
# All Rights Reserved.
#
# This program is free software; you can modify and/or redistribute it
# under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 3 with
# attribution addendums as found in the LICENSE.txt

require_relative 'autohotkey.rb'
autohotkey('CmdTlmServer', 'cmd_tlm_server.ahk') do
  require 'cosmos/tools/cmd_tlm_server/cmd_tlm_server_gui'
  Cosmos::CmdTlmServerGui.run
  good_files = 0
  Dir["autohotkey/outputs/logs/*.txt"].each do |file|
    if file =~ /server_messages/
      if File.size(file) == 0
        raise "CmdTlmServer message logs not written"
      else
        good_files += 1
      end
    end
  end
  raise "No CmdTlmServer message logs found" unless good_files > 0
end

