#!/usr/bin/env ruby
# encoding: ascii-8bit

# Copyright © 2014 Ball Aerospace & Technologies Corp.
# All Rights Reserved.
#
# This program is free software; you can modify and/or redistribute it
# under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 3 with
# attribution addendums as found in the LICENSE.txt

require_relative 'autohotkey.rb'
autohotkey('HandbookCreator', 'handbook_creator.ahk') do
  require 'cosmos/tools/handbook_creator/handbook_creator'
  Cosmos::HandbookCreator.run
end

# Clean up handbook output
Dir["autohotkey/outputs/handbooks/*.html"].each {|file| File.delete file }
Dir["autohotkey/outputs/handbooks/*.pdf"].each {|file| File.delete file }
