#!/usr/bin/env ruby
# encoding: ascii-8bit

# Copyright © 2014 Ball Aerospace & Technologies Corp.
# All Rights Reserved.
#
# This program is free software; you can modify and/or redistribute it
# under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 3 with
# attribution addendums as found in the LICENSE.txt

require_relative 'autohotkey.rb'
autohotkey('LimitsMonitor', 'limits_monitor.ahk') do
  require 'cosmos/tools/limits_monitor/limits_monitor'
  Cosmos::LimitsMonitor.run
end

# Clean up the Saved ignored items
File.delete('autohotkey/config/tools/limits_monitor/limits_monitor.txt')

