#!/usr/bin/env ruby
# encoding: ascii-8bit

# Copyright 2014 Ball Aerospace & Technologies Corp.
# All Rights Reserved.
#
# This program is free software; you can modify and/or redistribute it
# under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 3 with
# attribution addendums as found in the LICENSE.txt

require_relative 'autohotkey.rb'
autohotkey('ScriptRunner', 'script_runner.ahk') do
  require 'cosmos/tools/script_runner/script_runner'
  Cosmos::ScriptRunner.run
end

# Clean up by deleting the Save As script
File.delete('autohotkey/procedures/autohotkey.rb')

