#!/usr/bin/env ruby
# encoding: ascii-8bit

# Copyright © 2014 Ball Aerospace & Technologies Corp.
# All Rights Reserved.
#
# This program is free software; you can modify and/or redistribute it
# under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 3 with
# attribution addendums as found in the LICENSE.txt

require 'fileutils'
# Make a back up of the table config since we are going to update it
FileUtils.cp("autohotkey/config/tools/table_manager/OneDimensionalTable_def.txt",
             "autohotkey/config/tools/table_manager/OneDimensionalTable_def.bak")

require_relative 'autohotkey.rb'
autohotkey('TableManager', 'table_manager.ahk') do
  require 'cosmos/tools/table_manager/table_manager'
  Cosmos::TableManager.run
end

# Clean up table output
Dir["autohotkey/outputs/tables/*.dat"].each {|file| File.delete file }
Dir["autohotkey/outputs/tables/*.rpt"].each {|file| File.delete file }
# Restore the table config
File.delete("autohotkey/config/tools/table_manager/OneDimensionalTable_def.txt")
FileUtils.mv("autohotkey/config/tools/table_manager/OneDimensionalTable_def.bak",
             "autohotkey/config/tools/table_manager/OneDimensionalTable_def.txt")

