#!/usr/bin/env ruby
# encoding: ascii-8bit

# Copyright 2014 Ball Aerospace & Technologies Corp.
# All Rights Reserved.
#
# This program is free software; you can modify and/or redistribute it
# under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 3 with
# attribution addendums as found in the LICENSE.txt

require 'fileutils'
require_relative 'autohotkey.rb'
autohotkey('TableManager4') do
  require 'cosmos/tools/table_manager/table_manager'
  Cosmos::TableManager.run
end

# Clean up table output
raise "Output file not created!" unless File.exist?("autohotkey/ConfigTables.dat")
FileUtils.rm("autohotkey/ConfigTables.dat")
raise "Report file not created!" unless File.exist?("autohotkey/ConfigTables.csv")
FileUtils.rm("autohotkey/ConfigTables.csv")

