#!/usr/bin/env ruby
# encoding: ascii-8bit

# Copyright 2014 Ball Aerospace & Technologies Corp.
# All Rights Reserved.
#
# This program is free software; you can modify and/or redistribute it
# under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 3 with
# attribution addendums as found in the LICENSE.txt

require_relative 'autohotkey.rb'
autohotkey('TlmExtractor', 'tlm_extractor.ahk') do
  require 'cosmos/tools/tlm_extractor/tlm_extractor'
  Cosmos::TlmExtractor.run
end

# Clean up by deleting the file created by Save Text to File
File.delete('autohotkey/config/tools/tlm_extractor/tlm_extractor_unit_test.txt')
