#!/usr/bin/env ruby
# encoding: ascii-8bit

# Copyright © 2014 Ball Aerospace & Technologies Corp.
# All Rights Reserved.
#
# This program is free software; you can modify and/or redistribute it
# under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 3 with
# attribution addendums as found in the LICENSE.txt

require_relative 'autohotkey.rb'
autohotkey('TlmGrapher2', 'tlm_grapher2.ahk') do
  require 'cosmos/tools/cmd_tlm_server/cmd_tlm_server_gui'
  Thread.new do
    # Start up the CmdTlmServer first so it's going when we connect with TlmGrapher
    system("ruby.exe #{File.join(File.expand_path(File.dirname(__FILE__)),'CmdTlmServer')}")
  end
  sleep 3
  require 'cosmos/tools/tlm_grapher/tlm_grapher'
  Cosmos::TlmGrapher.run
end

