function getTodaysDate() {
  let today = new Date();
  let date = today.getFullYear() + '-' + (today.getMonth() + 1) + '-' + today.getDate();
  return date
}
// This returns the current hour then min is the minutes so you can easily get current data
function getCurrentTime(min) {
  let today = new Date();
  let time = today.getHours() + ":" + min + ":00"
  time = "14:" + min + ":00"
  return time
}
describe('TlmExtractor', () => {
  todaysDate = getTodaysDate()
  currentHour = getCurrentTime('00')
  currentHourPlus = getCurrentTime('15')
  it('Standard CSV output', function () {
    cy.visit('/telemetry-extractor')
    cy.hideNav()
    cy.get('[data-test=startdate]').type(todaysDate)
    cy.focused().click()
    cy.get('[data-test=enddate]').type(todaysDate)
    cy.focused().click()
    cy.get('[data-test=starttime]').type(currentHour)
    cy.focused().click()
    cy.get('[data-test=endtime]').type(currentHourPlus)
    cy.focused().click()
    cy.selectTargetPacketItem('INST', 'HEALTH_STATUS', 'TEMP1')
    cy.contains('Add Item').click()
    cy.selectTargetPacketItem('INST', 'HEALTH_STATUS', 'TEMP2')
    cy.contains('Add Item').click()
    cy.contains('Process').click()
    cy.wait(3000)
    cy.contains('Download File').click()
  })
  it('Tab delimited output', function () {
    cy.visit('/telemetry-extractor')
    cy.hideNav()
    cy.get('.v-toolbar')
      .contains('File')
      .click()
    cy.contains(/^Tab Delimited File$/).click()
    cy.get('[data-test=startdate]').type(todaysDate)
    cy.focused().click()
    cy.get('[data-test=enddate]').type(todaysDate)
    cy.focused().click()
    cy.get('[data-test=starttime]').type(currentHour)
    cy.focused().click()
    cy.get('[data-test=endtime]').type(currentHourPlus)
    cy.focused().click()
    cy.selectTargetPacketItem('INST', 'HEALTH_STATUS', 'TEMP1')
    cy.contains('Add Item').click()
    cy.selectTargetPacketItem('INST', 'HEALTH_STATUS', 'TEMP2')
    cy.contains('Add Item').click()
    cy.contains('Process').click()
    cy.wait(2000)
    cy.contains('Download File').click()
  })
  it('Full Column Names in output', function () {
    cy.visit('/telemetry-extractor')
    cy.hideNav()
    cy.get('.v-toolbar')
      .contains('File')
      .click()
    cy.contains(/^Use Full Column Names$/).click()
    cy.get('[data-test=startdate]').type(todaysDate)
    cy.focused().click()
    cy.get('[data-test=enddate]').type(todaysDate)
    cy.focused().click()
    cy.get('[data-test=starttime]').type(currentHour)
    cy.focused().click()
    cy.get('[data-test=endtime]').type(currentHourPlus)
    cy.focused().click()
    cy.selectTargetPacketItem('INST', 'HEALTH_STATUS', 'TEMP1')
    cy.contains('Add Item').click()
    cy.selectTargetPacketItem('INST', 'HEALTH_STATUS', 'TEMP2')
    cy.contains('Add Item').click()
    cy.contains('Process').click()
    cy.wait(2000)
    cy.contains('Download File').click()
  })
  it('Use Matlab Headers TSV output', function () {
    cy.visit('/telemetry-extractor')
    cy.hideNav()
    cy.get('.v-toolbar')
      .contains('File')
      .click()
    cy.contains(/^Tab Delimited File$/).click()
    cy.get('.v-toolbar')
      .contains('Mode')
      .click()
    cy.contains(/^Use Matlab Header$/).click()
    cy.get('[data-test=startdate]').type(todaysDate)
    cy.focused().click()
    cy.get('[data-test=enddate]').type(todaysDate)
    cy.focused().click()
    cy.get('[data-test=starttime]').type(currentHour)
    cy.focused().click()
    cy.get('[data-test=endtime]').type(currentHourPlus)
    cy.focused().click()
    cy.selectTargetPacketItem('INST', 'ADCS', 'Q1')
    cy.contains('Add Item').click()
    cy.selectTargetPacketItem('INST', 'ADCS', 'Q2')
    cy.contains('Add Item').click()
    cy.selectTargetPacketItem('INST', 'ADCS', 'PACKET_TIMEFORMATTED')
    cy.contains('Add Item').click()
    cy.contains('Process').click()
    cy.wait(5000)
    cy.contains('Download File').click()
  })
  it('Duplicate Item Triggers Warning', function () {
    cy.visit('/telemetry-extractor')
    cy.hideNav()
    cy.get('[data-test=startdate]').type(todaysDate)
    cy.focused().click()
    cy.get('[data-test=enddate]').type(todaysDate)
    cy.focused().click()
    cy.get('[data-test=starttime]').type(currentHour)
    cy.focused().click()
    cy.get('[data-test=endtime]').type(currentHourPlus)
    cy.focused().click()
    // Add the first item, INST/ADCS/CCSDSVER
    cy.contains('Add Item').click()
    cy.contains('Add Item').click()
    cy.contains('This item has already been added').should('be.visible')
  })

})
