#!/usr/bin/env ruby
# encoding: ascii-8bit

# Copyright 2014 Ball Aerospace & Technologies Corp.
# All Rights Reserved.
#
# This program is free software; you can modify and/or redistribute it
# under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 3 with
# attribution addendums as found in the LICENSE.txt

require 'cosmos'
require 'cosmos/tools/cmd_tlm_server/cmd_tlm_server_gui'

require 'memory_profiler'
report = MemoryProfiler.report do
  Cosmos::CmdTlmServerGui.run
end
File.open(File.build_timestamped_filename(%w(cts memory)),'w') {|file| report.pretty_print(file) }

