PLUGIN_NAME = Dir['*.gemspec'][0].split('.')[0..-2].join('.')

task :require_version do
  unless ENV['VERSION']
    puts "VERSION is required: rake <task> VERSION=X.X.X"
    exit 1
  end
end

task :docker_build do
  system("gem build #{PLUGIN_NAME}")
end

task :build => [:require_version] do
  _, platform, *_ = RUBY_PLATFORM.split("-")
  if platform == 'mswin32' or platform == 'mingw32'
    puts "Warning: Building gem on Windows will lose file permissions"
  end
  system("docker run -v %cd%:/cosmos/plugins -w /cosmos/plugins cosmos-base rake docker_build VERSION=%VERSION%")
end
