cmd("<%= target_name %> ABORT")
cmd_no_range_check("<%= target_name %> COLLECT with TYPE NORMAL, TEMP 100")
cmd_no_hazardous_check("<%= target_name %> CLEAR")
cmd_no_checks("<%= target_name %> COLLECT with TYPE SPECIAL, TEMP 100.0")
cmd_raw("<%= target_name %> ABORT")
cmd_raw_no_range_check("<%= target_name %> COLLECT with TYPE 0, TEMP 100")
cmd_raw_no_hazardous_check("<%= target_name %> CLEAR")
cmd_raw_no_checks("<%= target_name %> COLLECT with TYPE 1, TEMP 100.0")
check("<%= target_name %> ADCS BIASX == 100")
check_formatted("<%= target_name %> ADCS BIASX == 100")
check_with_units("<%= target_name %> ADCS BIASX == 100")
check_raw("<%= target_name %> ADCS BIASX == 100")
check_tolerance("<%= target_name %> ADCS BIASX", 5, 0.5)
check_tolerance_raw("<%= target_name %> ADCS BIASX", 5, 0.5)
check_expression("true == false")
wait
wait 5
wait("<%= target_name %> ADCS BIASX > 100", 5)
wait_raw("<%= target_name %> ADCS BIASX > 100", 5)
wait_tolerance("<%= target_name %> ADCS BIASX", 5, 0.5, 5)
wait_tolerance_raw("<%= target_name %> ADCS BIASX", 5, 0.5, 5)
wait_expression("true == false", 5)
wait_packet("<%= target_name %>","ADCS", 2, 5)
wait_check("<%= target_name %> ADCS BIASX == 100", 5)
wait_check_raw("<%= target_name %> ADCS BIASX == 100", 5)
wait_check_tolerance("<%= target_name %> ADCS BIASX", 5, 0.5, 5)
wait_check_tolerance_raw("<%= target_name %> ADCS BIASX", 5, 0.5, 5)
wait_check_expression("true == false", 5)
wait_check_packet("<%= target_name %>","ADCS", 2, 5)
